spring:
  datasource:
    url: jdbc:mysql://localhost/blog?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080
